development:
  mail_user_name: <%= ENV['MAIL_USER_NAME'] %>
  mail_password: <%= ENV['MAIL_PASSWORD'] %>
  mail_address: <%= ENV['MAIL_ADDRESS'] %>
  mail_domain: <%= ENV['MAIL_DOMAIN'] %>
  mail_port: <%= ENV['MAIL_PORT'] %>
  mail_authentication: <%= ENV['MAIL_AUTHENTICATION'] %>
production:
  mail_user_name: <%= ENV['MAIL_USER_NAME'] %>
  mail_password: <%= ENV['MAIL_PASSWORD'] %>
  mail_address: <%= ENV['MAIL_ADDRESS'] %>
  mail_domain: <%= ENV['MAIL_DOMAIN'] %>
  mail_port: <%= ENV['MAIL_PORT'] %>
  mail_authentication: <%= ENV['MAIL_AUTHENTICATION'] %>
production:
  mail_user_name: <%= ENV['MAIL_USER_NAME'] %>
  mail_password: <%= ENV['MAIL_PASSWORD'] %>
  mail_address: <%= ENV['MAIL_ADDRESS'] %>
  mail_domain: <%= ENV['MAIL_DOMAIN'] %>
  mail_port: <%= ENV['MAIL_PORT'] %>
  mail_authentication: <%= ENV['MAIL_AUTHENTICATION'] %>